#! /bin/sh

case $# in
    0|1)  echo "usage: `basename $0` casket dovecot-uidlist ..."; exit 1
esac

casket=$1
shift

for uidlist in "$@"; do
    dir=`dirname ${uidlist}`
    sed '1,$s|^\([^ ]*\) [^:]*:\(.*\)|'${dir}/cur/'\2	\1|' ${uidlist} | \
    estcmd gather -fm -px imap-uid ${casket} -
done
